/* Generated By:JavaCC: Do not edit this line. IntParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface IntParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDENTIFIER = 3;
  /** RegularExpression Id. */
  int NUMBER = 4;
  /** RegularExpression Id. */
  int SEMICOLON = 5;
  /** RegularExpression Id. */
  int EQUALS = 6;
  /** RegularExpression Id. */
  int L_PAREN = 7;
  /** RegularExpression Id. */
  int R_PAREN = 8;
  /** RegularExpression Id. */
  int INT = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<IDENTIFIER>",
    "<NUMBER>",
    "\";\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"INT\"",
  };

}
