/* Generated By:JavaCC: Do not edit this line. IntParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface IntParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDENTIFIER = 10;
  /** RegularExpression Id. */
  int INTEGER = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"::\"",
    "\";\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "<IDENTIFIER>",
    "<INTEGER>",
  };

}
